# Generated by Django 3.2.2 on 2022-07-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220730_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicacao_post',
            field=models.BooleanField(default=False, verbose_name='Publicacao Status'),
        ),
    ]
