# Generated by Django 3.2.2 on 2022-07-30 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_titulo_post'),
        ('comentarios', '0002_auto_20220730_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='post_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post'),
        ),
    ]
