# Generated by Django 3.2.2 on 2022-07-30 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0002_categoria_autor_cat_categoria_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='autor_cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_cat',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='status_cat',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
